### ISSUE TITLE
Configurar CI para rodar os testes

### ISSUE THREAD

**Issue by nandosousafr** [contribyard/livetools#10]
- [ ] Rodar rspec

Exemplo:

```yml
version: 2.1
executors:
  default:
    docker:
      - image: cimg/ruby:3.0.2
        environment:
            RAILS_ENV: test
            DATABASE_URL: postgres://postgres:@127.0.0.1/circle_test
            BUNDLE_PATH: vendor/bundle
      - image: postgres:9.6.2-alpine
jobs:
  rspec:
    executor: default
    steps:
      - checkout
      - run: bundle install -j$(nproc)
      - run:
          command: bundle exec rspec
workflows:
  version: 2
  build_test_and_security:
    jobs:
      - rspec
```
